name: Docker Image CI DEV

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Build the Docker image
      run: |
        docker build -t flask-calculator-pipeline-dev cloudspace/
        docker tag flask-calculator-pipeline-dev marcusb2006/flask-calculator-pipeline-dev:v1
        docker push marcusb2006/flask-calculator-pipeline-dev:v1
      
